### ISSUE TITLE
typo in           return `${propertyName} must be an MongoDB ObjectId instance`;

### ISSUE THREAD

**Issue by akaNightmare** [vlbras/nestjs-object-id#1]
need replace with
          return `${propertyName} must be a MongoDB ObjectId instance`;

**Comment by vlbras** [comment]
Thank you for your attention. You can update package to v1.2.2, which contains a fix ✅

**Comment by vlbras** [comment]
Hey @akaNightmare I released `v2.0.1`, were I fixed some bugs and introduced `@ParseObjectId()`. Highly recommend you to update `nestjs-object-id` in your projects
