### ISSUE TITLE
Nest can't resolve dependencies of the ParseObjectIdPipe (?)

### ISSUE THREAD

**Issue by shohjahon1code** [vlbras/nestjs-object-id#3]
I am facing dependency injection error while using this package. how do i fix this. this error was there before, it appeared recently, my whole project stopped working because of this error.

**Comment by vlbras** [comment]
Hi @shohjahon1code, could you update `nestjs-object-id` to latest version: `npm i nestjs-object-id@latest` and check if problem is solved?
