### ISSUE TITLE
IsObjectIdPipe is throwing error in the terminal

### ISSUE THREAD

**Issue by somnathPrasad** [vlbras/nestjs-object-id#4]
![image](https://github.com/user-attachments/assets/730b6f1c-3098-4289-bce2-92c121bfe27e)
![image](https://github.com/user-attachments/assets/712f6d39-699e-46e1-9cd9-4841158987cf)
![image](https://github.com/user-attachments/assets/b8ff01f0-4221-452f-bb02-7259511ccfea)

When using the IsObjectIdPipe in the @Param decorator, the server is crashing and the BadRequestException error is shown their instead of on the response

**Comment by somnathPrasad** [comment]
Hey @vlbras  help me with this. Am i doing anything wrong ?

**Comment by vlbras** [comment]
Hi @somnathPrasad , could you update nestjs-object-id to latest version: npm i nestjs-object-id@latest and check if problem is solved?

**Comment by vlbras** [comment]
If not, you can reach me in Telegram https://t.me/vlbras, we can catch and figure it out.

**Comment by somnathPrasad** [comment]
i only tried it in the latest version

**Comment by vlbras** [comment]
which NestJS version do you use?

**Comment by somnathPrasad** [comment]
I am using the latest one.
```
"@nestjs/core": "^9.0.0",
"@nestjs/common": "^9.0.0",
```

**Comment by vlbras** [comment]
Unfortunately, it's not the latest version. As mentioned in [the documentation](https://github.com/vlbras/nestjs-object-id?tab=readme-ov-file#pipes), you need to use at least `@nestjs/common@10.2.7`.

You can update NestJs version following [this guide](https://dev.to/amirfakour/how-to-upgrade-nestjs-9-to-10-a-developers-guide-32kk).
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/2d56cd3b-bac1-462a-90a0-11d8aa27be35">

**Comment by somnathPrasad** [comment]
Ohh my bad. Thank a lot

**Comment by vlbras** [comment]
@somnathPrasad, if you don't want to update NestJS, you can still achieve objectId validation with `nestjs-object-id`. You just need to create params dto.
```ts
import { IsObjectId } from 'nestjs-object-id';

export class GetPostParamsDto {
  @IsObjectId()
  public id: string;
}
```
And use it in a controller method.
```ts
  @Get(':id')
  public async getPost(@Param() { id }: GetPostParamsDto): Promise<PostModel> {
    return this.postQueryService.getPost(id);
  }
```

**Comment by somnathPrasad** [comment]
I updated my nestjs to 10. Now it is working

**Comment by alex-reusables** [comment]
@vlbras I am seeing the error mentioned here, I am on version `@nestjs/common@11.1.0`, is it expected that this package would throw this error if on a version of nestjs/common other than 10?

**Comment by vlbras** [comment]
@alex-reusables @nestjs/common@11.1.0 introduced breaking changes. I have updated the package to be compatible with the latest NestJS version. Could you please update the nestjs-object-id package to its latest version and check again?

**Comment by sahiljain2497** [comment]
version 3 works perfectly with @nestjs/common@11 . thanks. Was trying to create a global filter to resolve this with version 2 but this update fixes that.
